### ISSUE TITLE
视频时间长度不正确问题 Incorrect video length/duration issue

### ISSUE THREAD

**Issue by JGH-GOU** [higankanshi/Meta.Vlc#109]
我发现有些视频无法取得正确的长度时间，
而且有时Position的值会超过1，
貌似是libVLC本身的问题，
请问有解决办法吗?
谢谢。

I found some videos can’t get the correct length.
And sometimes Position value will be more than 1.
It looks like a bug in libVLC.
Is there a solution?
Thanks.

**Comment by higankanshi** [comment]
唔，如果是可以去 VLC 的论坛（[Development around libVLC](https://forum.videolan.org/viewforum.php?f=32)）提问。
以我的经历来看一般是流视频的影片可能没有长度，特指某些实时流视频。一般的都有，不知道你是什么格式。

**Comment by JGH-GOU** [comment]
我的视频是AVI格式，实际长度为4个小时，但是Length属性却只有2小时，
使用官方vlc播放器也是一样的结果.

My video is AVI format, the actual length is 4 hours, but the Length property only get 2 hours.
Using the official VLC player gives the same result.

**Comment by higankanshi** [comment]
唔，我觉得你可以去 VLC 论坛提这个 issue...
对于 VLC 的 bug 我无能为力...OTZ
