### ISSUE TITLE
System.NullReferenceException in VlcPlayer and ThreadSeparatedImage objects

### ISSUE THREAD

**Issue by Vasto** [higankanshi/Meta.Vlc#117]
Hello,

I'm using an older version of xZune.VLC in my project and it's working fine. Though I've noticed that you have improved many things in the recent commits, and I've decided to upgrade my version of the library. Unfortunately the new multithread compatiblity features seems to cause a lot of issues with my older approach to using the VlcPlayer control. The project I'm working is quite complex, and giving all details would be very difficult, so at least I will try to describe briefly how im using the VlcPlayer control. 

I'm trying to follow a MVVM pattern in my project. In the view model i have a VlcPlayer object which is bound to the content property of a ContentControl in the View. I have to do it in that way, because it provides me a better control of things than having VlcPlayer defined in XAML and it works well. 

One functionality which I have to provide is the ability to switch to the fullscreen mode on the fly, without realoading the stream. After trying many approaches, the best one for me was to create a new window with appropertiate settings, and pass my VlcPlayer object to it's view model and keep it there, until user exits this mode. In the window the VlcPlayer object is bound to ContentControl in a View in the same way as I described earlier. To get it working, I have to pass the VlcControl object between view models of my camera view and the fullscreen view. It requires to set the VlcControl property of a previous view model to null, so it is not bound to the inactive view anymore. This approach worked fine with older versions of xZune.VLC. Unfortunately in new versions it causes a NullReferenceException in the ThreadSeparatedImage class on the SeparateThreadDispatcher property or in the VideoLockCallback and VideoFormatCallback methods of VlcPalyer when accessing the DisplayThreadDispatcher. It looks like the VlcControl's DisplayThreadDispatcher property is set to null at some point, when a VlcPlayer object is rebound to a ContentControl in another View.

Any idea how to solve this issue?

**Comment by Divaite** [comment]
Hi.

I experienced the same problem and unfortunately there is nothing you can do without code fixes.
At first on each SeparateThreadDispatcher.Invoke() should be check if SeparateThreadDispatcher is not null. Also I do believe that checking if InternalImageControl is not null should be placed inside SeparateThreadDispatcher.Invoke().

If someone will do this fix, I'd recommend also have a look at HandleManager, sometimes it can throws IndexOutOfRangeException when new IVlcObject is adding. Do not know what causes this issue, but ConcurrentDictionary helps a lot, but cannot be used in projects below .net 4.0.

After this modification looks like this issue is gone, I'd like to share my changes for the project, but I didn't care about compatibility and it's done only for .net 4.5 using C#6 features.

**Comment by higankanshi** [comment]
If you want use VlcPlayer in CS code, not XAML(you will not add VlcPlayer to visual tree).
Please see this wiki (Use VlcPlayer with other controls)[https://github.com/higankanshi/xZune.Vlc/wiki/Use-VlcPlayer-with-other-controls].

If you use `new VlcPlayer()` not `new VlcPlayer(bool)` or `new VlcPlayer(Dispatcher)`, SeparateThreadDispatcher will be set after VlcPlayer have added to visual tree.
So it will be null until you add it to visual tree.

But if you use `new VlcPlayer(bool)` or `new VlcPlayer(Dispatcher)`, VlcPlayer will work on custom mode. if you use SeparateThreadImage to render video, use `new VlcPlayer(true)`, VlcPlayer will work on SeparateThreadImage mode, the VideoSource only can be use in SeparateThreadImage. if you use Image or ImageBrush to render video,  `new VlcPlayer(false)` or  `new VlcPlayer(Image.Dispatcher)` VlcPlayer will create VideoSource for UI thread or your control thread.

Ummm....I will add some null check in my code.
