### ISSUE TITLE
using vlcplayer with image

### ISSUE THREAD

**Issue by mylady** [higankanshi/Meta.Vlc#118]
using image with vlcplayer's videosource as input
after wpf window close with ALT+F4, the process is still hanging

here's code:

```c#
 Player = new VlcPlayer(ImageShow.Dispatcher);
 Player.Initialize(App.LibVlcPath, new string[] { "-I", "dummy", "--ignore-config", "--no-video-title" });
 Player.Margin = new Thickness(0);
 Player.Padding = new Thickness(0);
 Player.CreateMode = PlayerCreateMode.NewVlcInstance;
 Player.VlcMediaPlayer.EndReached += VlcMediaPlayer_EndReached;
 Player.VlcMediaPlayer.EncounteredError += VlcMediaPlayer_EncounteredError;
 Player.VideoSourceChanged += Player_VideoSourceChanged;
 ImageShow.Source = Player.VideoSource;
 ImageShow.Stretch = Stretch.Fill;
```
I stopped video play in custom control unload event and get vlcplayer disposed
but still process wont exit,there might be some thread running

**Comment by higankanshi** [comment]
Have you update the nugget package?

**Comment by mylady** [comment]
yes,i upgraded the nuget package and version as below:

xZune.Vlc 16.04.17
xZune.Vlc.Lib 15.11.24
xZune.Vlc.Wpf 16.04.17
.netFramework 4.0

**Comment by higankanshi** [comment]
If you use Image to render Video, you should call the Stop method in the thread which is not UI thread.
VlcPlayer.Dispose() call the Stop method, so you should use it async too.

```CSharp
Task.Run(() =>
{
    Player.Dispose();
});
```

**Comment by mylady** [comment]
ok, i have it tested and works fine, thx :)
