### ISSUE TITLE
Translating xml documentation from chinese into English - to help non Chinese users

### ISSUE THREAD

**Issue by epsi1on** [higankanshi/Meta.Vlc#119]
Hi,
As you may have seen, many parts of XML documentation inside the code is in Chinese language. For example:

![untitled](https://cloud.githubusercontent.com/assets/7839141/14808696/c342d382-0b9c-11e6-94da-dc0a96b6d0d4.png)

I would like to suggest translate the strings inside library from Chinese to English. 
I can do part of work, as this:
1- Use google translate to translate Chinese sentences to English.
2- Control all translated senteses line by line and with hand and fix translation mistakes by hand

But someone who knows both Chinese and English, should make a final revision on method documentations after translation.
Please let me know if anyone who is familiar to both Chinese and English, can do the final revision. Then i'll start...

Thanks

**Comment by higankanshi** [comment]
Thanks for your enthusiasm.

You can see document of [libvlc](http://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc.html), those Chinese all translate from those document.

If you want provide English comment, please create a PR.
