### ISSUE TITLE
null reference exception in VideoFormatCallback

### ISSUE THREAD

**Issue by epsi1on** [higankanshi/Meta.Vlc#120]
Hi,
When i Play() a player control on a window which is just initialized - but not loaded yet, i do get null reference exception on `VideoFormatCallback` method of Vlc WPF control :

![untitled](https://cloud.githubusercontent.com/assets/7839141/14846675/34e6bf34-0c7a-11e6-9937-17ee47175b3b.png)
Problem is that "_context" is `null`, "VlcPlayer.DisplayThreadDispatcher" is `null` also "vlcPlayer._customDisplayThreadDispatcher" is `null` too. i did temporarily fixed the problem by adding this line of code into `xZune.Vlc.Wpf.VlcPlayer` class:

`_customDisplayThreadDispatcher = Application.Current.Dispatcher;`

**Comment by higankanshi** [comment]
Please see the #117 and this wiki: [Use VlcPlayer with other controls](https://github.com/higankanshi/xZune.Vlc/wiki/Use-VlcPlayer-with-other-controls)
