### ISSUE TITLE
Viewing webcam input

### ISSUE THREAD

**Issue by bbuckwal** [higankanshi/Meta.Vlc#121]
I am trying to use VlcPlayer to view webcam input. I can see the video fine it just has a significant lag compared to using the stand alone VLC app. When I stream video from a network address using VlcPlayer the performance is fine. Any ideas? Thanks.

private void Window_Loaded(object sender, RoutedEventArgs e)
{
  Uri path = new Uri(@"dshow://");

  // Set up your options here
  Player.VlcOption = new string[] { @" :dshow-vdev=Logitech HD Pro Webcam C920 :dshow-adev=Microphone (HD Pro Webcam C920) :dshow-size=320x240 :live-caching=300" };

  Player.Stop();
  Player.LoadMedia(path);

  Player.Play();
}

**Comment by higankanshi** [comment]
Maybe you can try `Player.LoadMediaWithOptions()`.

**Comment by bbuckwal** [comment]
I tried Player.LoadMediaWithOptions() and get the same lag. It's looks like a really low framerate. I tried the VLC active x control and everything is fine.

**Comment by higankanshi** [comment]
Player.VlcOption is must be set before the player loaded, I think you can try set it in XAML code...not in window loaded event.
