### ISSUE TITLE
full screen mode - question - 

### ISSUE THREAD

**Issue by gobne** [higankanshi/Meta.Vlc#123]
When i try to switch in full screen mode
Audio remains but player background becomes black.

there is my code:

               if (!isFullScreen)
                {
                    myGrid.Children.Remove(myPlayer);
                    myPlayer.Width = myPlayer.MaxWidth; 
                    myPlayer.Height = myPlayer.MaxHeight; 
                    Application.Current.MainWindow.WindowStyle = WindowStyle.None;
                    Application.Current.MainWindow.WindowState = WindowState.Maximized;
                    myPlayer.Stretch = Stretch.Fill;
                    myPlayer.StretchDirection = StretchDirection.Both;
                    this.Content = myPlayer;
                    isFullScreen = true;
                }
                else
                {
                    this.Content = myGrid;
                    myPlayer.Width = Application.Current.MainWindow.Width - playerStatus.Width;
                    myPlayer.Height = Application.Current.MainWindow.Height - playerStatus.Height;
                    myGrid.Children.Insert(0, myPlayer);
                    Application.Current.MainWindow.WindowStyle = WindowStyle.SingleBorderWindow;
                    Application.Current.MainWindow.WindowState = WindowState.Normal;
                    isFullScreen = false;
                }

Thank you for reply.

**Comment by shaunthasheep** [comment]
here's the code I use.. I use NotifyPropertyChanged to update the UI in this code. GetNewFullscreenWindow just returns a new window with default properties. 
```
        public VlcPlayer MediaPlayerView { get { return fullscreen ? null : mediaPlayer; } }
        public UserControl PlayerOverlayView { get { return fullscreen ? null : playerOverlay; } }

        internal void ToggleFull()
        {
            fullscreen = !fullscreen;
            NotifyChange("IsFullScreen");
            if (fullscreen)
            {

                fullWindow = Hooligan.Theme.HooliganCurrentTheme.CurrentTheme.GetNewFullscreenWindow();
                fullWindow.Topmost = true;
                fullWindow.WindowStyle = WindowStyle.None;
                fullWindow.ResizeMode = ResizeMode.NoResize;
                fullWindow.WindowStartupLocation = System.Windows.WindowStartupLocation.Manual;

                fullWindow.Top = this.hooligan.hooliganMainWindow.Top;
                fullWindow.Left = this.hooligan.hooliganMainWindow.Left;

                NotifyChange("MediaPlayerView");
                NotifyChange("PlayerOverlayView");
                Grid root = new Grid();
                root.Children.Add(mediaPlayer);
                root.Children.Add(playerOverlay);
                fullWindow.Content = root;
                fullWindow.Show();

                fullWindow.WindowState = WindowState.Maximized;

            }
            else
            {
                Grid root = fullWindow.Content as Grid;
                root.Children.Clear();
                fullWindow.Content = null;
                NotifyChange("MediaPlayerView");
                NotifyChange("PlayerOverlayView");
                fullWindow.Close();
                fullWindow = null;
            }
        }
```

**Comment by gobne** [comment]
I solved. Thank you so much :)

**Comment by shaunthasheep** [comment]
I updated to the newest version and my code broke. How did you fix it?

**Comment by gobne** [comment]
I removed these lines from my code:

           if (!isFullScreen)
            {
               // myGrid.Children.Remove(myPlayer);                
               // this.Content = myPlayer;
            }
            else
            {
            //    this.Content = myGrid;
            //    myGrid.Children.Insert(0, myPlayer);
            }

I let myPlayer as grid's child.

if I put these lines, screen becomes black.

P.S. sorry for my english :)
