### ISSUE TITLE
Can't take snapshot.

### ISSUE THREAD

**Issue by davidniu1988** [higankanshi/Meta.Vlc#127]
Hi,
I want to take a snapshot in Meta.Vlc.Wpf.Sample - .Net 4.5, but it shows this and can't take snapshot. Any ideas? Thank you.
![image](https://cloud.githubusercontent.com/assets/17900672/15390013/1b33f56a-1dec-11e6-9ccf-690a0d45b43a.png)

**Comment by shaunthasheep** [comment]
The error is something about the calling thread being different but I got it to work with this code:
'''
            mediaPlayer.VideoSource.Dispatcher.Invoke(() =>
            {
                var png = new PngBitmapEncoder();
                png.Frames.Add(BitmapFrame.Create(mediaPlayer.VideoSource));
                using (Stream fileStream = File.Create(@"D:\test.png"))
                {
                    png.Save(fileStream);
                }
            });
'''
