### ISSUE TITLE
Unable to Change Audio Device

### ISSUE THREAD

**Issue by pyromanci** [higankanshi/Meta.Vlc#129]
Let me start off and say Meta.Vlc has solved many headaches with one of projects. 

I've been trying to figure out how to switch audio device. I've tired several approaches, but none seem to work.

One of the approach i took was simply:
`VlcPlayer.SetAudioDevice(_directSound, _device);`

Another approach was simply setting the option during the initialize. 
```
VlcPlayer.Initialize(_LibVLCPath, "-I", "dummy", "--ignore-config", "--no-video-title", "--file-logging",
                "--logfile=vlclog.txt", "--verbose=2", "--no-sub-autodetect-file",
                 "--directx-audio-device=XXXX
);
```

Neither have worked, so i'm left stumped as i was able to do it with VLC it's self without and problems. 

Has anyone been able to get it to work?

**Comment by higankanshi** [comment]
See #73 , maybe it can help you.

**Comment by pyromanci** [comment]
I did look at that. And it's is basically what i'm doing. I have tired 2.2.0 - 3.0.0 LibVLc version. 

Here is my code:
```
public partial class MusicPlayer : UserControl
{
	public MusicPlayer()
	{
		StaticControler.VlcPlayer = new VlcPlayer(PlayerImage.Dispatcher);
		StaticControler.VlcPlayer.Initialize(StaticControler.LibVLCPath);
		StaticControler.VlcPlayer.VideoSourceChanged += PlayerOnVideoSourceChanged;
		
		AudioDevice _device = null;
		var devices = Brain.VlcPlayer.EnumAudioDeviceList();
		foreach (var d in devices)
		{
			if (d.Description == "Speakers (Turtle Beach PX22)")
				_device = d;
		}
		
		StaticControler.VlcPlayer.SetAudioDevice(null, _device);
	}
	
	private void PlayerOnVideoSourceChanged(object sender, VideoSourceChangedEventArgs e)
	{
		PlayerImage.Dispatcher.BeginInvoke(new Action(() =>
		{
			PlayerImage.Source = e.NewVideoSource;
		}));
	}
	
	private void playPasueBtn_Click(object sender, RoutedEventArgs e)
	{
		if (Brain.VlcPlayer.VlcMediaPlayer.IsPlaying)
			Brain.VlcPlayer.PauseOrResume();
		else
		{
			//TODO Playlist control.
			Brain.VlcPlayer.Stop();
			Brain.VlcPlayer.LoadMedia(new Uri("http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi"));
			Thread.Sleep(1000);
			Brain.VlcPlayer.Play();
		}
	}
}
```

Now what i've done is set my PC's default Playback to something that was not connected. Then As shown  above find the AudioDevice that's labeled my Turtle Beach PX22 headset. 

When i actually hit the play button I do not get any sound. If i plug speakers into the playback device that was not connected I do get audio then. So it appears that the despite calling the `SetAudioDevice()` function it continue's to play out the Default Audio device of the PC.

**Comment by higankanshi** [comment]
You can try to use GetAudioDevice() after you set device, check it is applied changes or not, and check GetAudioDeviceList() the device is available for current audio output(WASAPI, DSound or other).

**Comment by pyromanci** [comment]
Well I switch I tired 2.2.1 and 3.0.0 LibVLC versions and the `GetAudioDevice()` would throw the following error. 
`Function "libvlc_audio_output_device_get" isn't available on current version LibVlc.`

Now I did notice that the PX22 were only listed listed under the `waveout` module. So I changed the `SetAudioDevice()` line in my code to this:

```
	AudioOutput _output = null;
	AudioDevice _device = null;
	var outputs = Brain.VlcPlayer.GetAudioOutputList();

	foreach (var o in outputs)
	{
		if (o.Name.StartsWith("adummy") || o.Name.StartsWith("afile") || o.Name.StartsWith("amem"))
			continue;

		if (o.Name == "waveout")
			_output = o;

		var outDevices2 = Brain.VlcPlayer.GetAudioDeviceList(o);
		foreach (var d in outDevices2)
		{
			if (d.Description.Contains("Turtle Beach PX22"))
				_device = d;
		}
	}
	
	Brain.VlcPlayer.SetAudioDevice(_output, _device);
```

This resulted in the same problem. Audio was not coming out the Head set as it should. 

I'm wondering if it has something to do with it being in a UserControl. As the user control was creating problems for me when doing the simple wpf markup like: 
` <wpf:VlcPlayer x:Name="Player" VlcOption="{StaticResource VlcOptions}" LibVlcPath="..\..\libvlc" EndBehavior="Nothing" Stretch="Fill"/>`

Which is why i'm using the the thread separated method.

**Comment by higankanshi** [comment]
ummm...No idea with it, but I am successful to switch my two audio card with those api...

I don't know what problems have been created in your UserControl, can you describe it ?

**Comment by pyromanci** [comment]
OK It is very strange. I decided to rule out all my extra code in my project. So I garbed the sample project from the repo. Then used the Nuget Libraries. Then tired to change the audio output again using just that. Still would not change the output. 

Here is the link to what i did. 
https://www.dropbox.com/s/762yvs0fo18tkk1/Meta.Vlc%20Tests.zip?dl=0

**Comment by pyromanci** [comment]
While continuing to investigate. I accidentally triped the code that changed the audio device in my project while a video was playing. This did in fact switch the device.

So I modified the Sample Code from the Git repo and added a bottom that would toggle back and forth between my speakers and my Headset. 

When the player first initializes. Didn't matter how many times you would click the button, it would not play in the correct audio device when the video starts playing. But once the video has started it will.

Updated Test code I was using: 
https://www.dropbox.com/s/762yvs0fo18tkk1/Meta.Vlc%20Tests.zip?dl=0

So for right now, i'm modifing my code to switch the device the moment the video starts playing, but that is not ideal nor do i think it's the correct method. since the playback is halted and resumed when switch a audio device.

**Comment by higankanshi** [comment]
I have tried your code, you can see, when I click "Audio" button, the different audio device will be used.

Headset
![headset](https://cloud.githubusercontent.com/assets/9367842/15919828/84b95e56-2e47-11e6-9a5c-110d6c83f10b.png)

S/PDIF
![pdif](https://cloud.githubusercontent.com/assets/9367842/15919830/8abc34e0-2e47-11e6-8a97-5a5b67a8dd0f.png)

**Comment by pyromanci** [comment]
Ok question what OS are you running? Win 10 Pro is what i've been running on.

There must be a explanation for why it runs differently for me.  Only thing i can think of a difference in OS but that would more then likely be the fault of LibVLC.

**Comment by higankanshi** [comment]
I'm Win 10 too...

**Comment by pyromanci** [comment]
Then i'm going to just chalk this up to a problem inside of libvlc then. Since it's the only thing at the moment that makes sense. I did noticed then when using the v3.0 when I got the  `Player.GetAudioDevice() `to work, before it would play would give me a Null.
