### ISSUE TITLE
the method uri.toHttpEncoding() is useless

### ISSUE THREAD

**Issue by reguez** [higankanshi/Meta.Vlc#132]
hello i found that that method you created to encode url is unessary as some url which are already encoded get's  messy and will cause a change in the link url  therefore  the video will not open  i found this issues in many sites and in youtube videos and i just replaced uri.toHttpEncoding to OriginalString and it works ! . i did report this issue to you in gitter

**Comment by higankanshi** [comment]
This method fixed #92 ...
Ummm...maybe we should convert to http encoding by ourselves...

**Comment by reguez** [comment]
it's not the same problem though , this time the link is already encoded try it yourself with youtube urls
