### ISSUE TITLE
After a while of usage

### ISSUE THREAD

**Issue by ITr1ckst3rI** [higankanshi/Meta.Vlc#133]
I seem to keep getting : 

Object reference not set to an instance of an object.
at Meta.Vlc.Wpf.VlcPlayer.VideoDisplayCallback(IntPtr opaque, IntPtr picture)

After loading, stopping and general use. unfortunatly that's my entire stacktrace for the issue. Any ideas?

**Comment by higankanshi** [comment]
How do you use VlcPlayer?
In xaml or your C# code?

**Comment by TroubleKiller** [comment]
In xaml,I have encountered this problem too .
"Object reference not set to an instance of an object."

**Comment by higankanshi** [comment]
Maybe you can include the source code of Meta.Vlc to your project, you can get more information of this issue.

**Comment by ITr1ckst3rI** [comment]
I build the WPF control in XML.

I use myControl.Stop along with myControl.loadMedia(new URI) and myControl.Play().

The strange this is the code doesn't break on any line in visual studio, it just full crashes. Doesn't give me a stack trace source of the crash either, only those two lines.

 I will see if I can replicate this issue outside of my app (Legally can't post source code). So far the only method of reproducing this error is to stop and reload the video player a bunch of times. So I will attempt to do that in a 20 second loop.

Also, anyone who gets an issue with object not set to reference of an object in you XAML code, this is NOT the same issue. Your issue is you're not pointing the WPF application to the vlcLibs correctly under the assembly.cs

**Comment by ITr1ckst3rI** [comment]
Thanks for the quick reply, higankanshi, Hopefully we can figure this out.

**Comment by ITr1ckst3rI** [comment]
Okay, I figure out the problem. 

If you have the wpf control hidden, and try to load media it will throw this error in the DLL.

**Comment by ITr1ckst3rI** [comment]
Okay, I figured out the issue. WPF Control being hidden, and trying to load the media into the hidden object will throw this error.

Sorry for bugging you, have a great day :+1:
