### ISSUE TITLE
After unloaded VlcPlayer control and then loading VlcPlayer,Play() is not working.

### ISSUE THREAD

**Issue by TroubleKiller** [higankanshi/Meta.Vlc#134]
In Xaml, VLCPlayer is in the page control, when page has initialized I loadMedia().And then play(),Video shows correctly.But when page unloaded and then load again ,play() does't work .In VlcPlayer.cs，VlcMediaPlayer throws following exception:
IsAdjustEnable = “VlcMediaPlayer.IsAdjustEnable”引发了类型“System.AccessViolationException”的异常

**Comment by higankanshi** [comment]
We fix it in 32fa8d74e840fe4a4dcad57630d9953b095d3dea, check it.
