### ISSUE TITLE
(Question) Fastest way to stop vlc player?

### ISSUE THREAD

**Issue by ITr1ckst3rI** [higankanshi/Meta.Vlc#136]
I was curious if anyone has a faster way of removing media and stopping vlc player other than .Stop()?

.Stop() after a while seems to take longer and longer (Reloading media into object after each stop) 

So, I was wondering if there were any methods to stopping the player faster. Such as just disposing the loaded media and reloading a new file, completely recreating the player(.Rebuild()) or anything at all.

**Comment by higankanshi** [comment]
Nope, but I have idea, we can rebuild a VlcMediaPlayer, but it is not a perfect way, some settings of VlcMediaPlayer need to reset.

**Comment by ITr1ckst3rI** [comment]
Anything would be helpful. If you have an idea I would love to hear it. :)
