### ISSUE TITLE
Stop event not fired when call player.stop() on RTSP stream

### ISSUE THREAD

**Issue by temka1234** [higankanshi/Meta.Vlc#137]
Hi!

I am using xZune.Vlc version 16.3.28.0.

When listening `StateChanged` of rtspPlayer only `MediaState.Playing` event firing.

```
rtspPlayer.StateChanged += new EventHandler<MediaState>>(rtspPlayer_StateChanged);
...
void rtspPlayer_StateChanged(object sender, ObjectEventArgs<MediaState> e)
{
    Console.WriteLine(e.Value);
}
```

Setting RTSP source
```
...
rtspPlayer.LoadMedia("rtsp://...");
...
```

This code not firing `MediaState.Stopped` or `MediaState.Ended`
```
...
rtspPlayer.Stop();
...
```

Whats i am doing wrong?

Thanks.

**Comment by higankanshi** [comment]
No idea with it, but you can try the Meta.Vlc 16.5.1
