### ISSUE TITLE
Not working adjust APIs in VlcMediaPlayer

### ISSUE THREAD

**Issue by hongseokwon** [higankanshi/Meta.Vlc#138]
Hi, I'm working video player, using meta.vlc.

So, I'm player add functions, brightnee, contrast, and gamma.
But, Not working.

follow code (view) ========================================

```
                       <Grid Grid.Row="0" >
                            <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
                                <StackPanel Orientation="Horizontal">
                                    <TextBlock>SDF</TextBlock>
                                    <Slider VerticalAlignment="Center"
                                            Width="300"
                                            Height="30"
                                            TickFrequency="0.00001"
                                            SmallChange="0.00001"
                                            LargeChange="0.00001"
                                            Margin="{StaticResource BaseThickness}"
                                            Maximum="1"
                                            Style="{DynamicResource FlatSlider}"
                                            Opacity="0.5"
                                            Value="{Binding Brightness}" />
                                </StackPanel>
                            </StackPanel>
                        </Grid>

```

(cs)

```
public float Brightness
{
	get { return VlcPlayer.VlcMediaPlayer.Brightness; }
	set
	{
		VlcPlayer.VlcMediaPlayer.Brightness = value;
		RaisePropertyChanged("Brightness");
	}
}
```

Full source code url : https://github.com/hongseokwon/StoneCircle-MediaPlayer/blob/master/StoneCircleMediaPlayerVlc/StoneCircleMediaPlayerVlc/MainWindow.xaml

What's problems???
I don't understand this problem...T_T
Help me please.

**Comment by higankanshi** [comment]
Set `VlcMediaPlayer.IsAdjustEnable` to `true` to enable video adjust.

**Comment by hongseokwon** [comment]
Ok. I'm set IsAdjustEnable to true.
But, Not working...T_T;
[Debug View Error](https://github.com/hongseokwon/StoneCircle-MediaPlayer/blob/master/IsAdjustEnableError.png)
What this happen???
Thanks for read.

**Comment by higankanshi** [comment]
You must set `IsAdjustEnable` while video is playing.

![qq 20160704223809](https://cloud.githubusercontent.com/assets/9367842/16564052/0598c1c0-4238-11e6-86b1-9209c5f1a8cc.png)

Set `Brightness` to 0.5
![qq 20160704223819](https://cloud.githubusercontent.com/assets/9367842/16564055/101ca238-4238-11e6-9ce5-b72e9498ab63.png)

**Comment by hongseokwon** [comment]
Ye, That's working.

follow code is work.
```
		public float Gamma
		{
			get { return MetaVlcPlayer.VlcMediaPlayer.Gamma; }
			set
			{
				MetaVlcPlayer.VlcMediaPlayer.IsAdjustEnable = true;
				MetaVlcPlayer.VlcMediaPlayer.Gamma = value;
				RaisePropertyChanged("Gamma");
			}
		}
```

Thanks a lot, higankanshi
