### ISSUE TITLE
Out of memory after a while on continuous video playback

### ISSUE THREAD

**Issue by Nikolas-LFDesigns** [higankanshi/Meta.Vlc#139]
Hello.
Having an issue with this lib in my WPF app, which is as subject stands prevents continuous playback.
The error is, like on CCTV case (#41): "System.Runtime.InteropServices.COMException (0x80070008): Insufficient memory to continue the execution of the program." exception in the VideoDisplayContext constructor while invoking Imaging.CreateBitmapSourceFromMemorySection(). But.. and it's a big but - we don't have a luxury of even 4 gb RAM most of the time, so no 64 bit love here.
Describing a playback procedure in case it's my fault:
 Creating a VlcPlayer object (with true in ctor) for each video (using stop()+dispose() to deinit it, also removing VideoSourceChanged event), binding VideoSource to the ThreadSeparatedImage and setting VideoSourceChanged like described.
In the code here https://github.com/higankanshi/Meta.Vlc/blob/02af7ca15604b950d213fe842b53bd13574fe4c9/Meta.Vlc.Wpf/VideoDisplayContext.cs#L62
I don't see an Image (that's InteropBitmap, a memory hog) got disposed or something, just set to null to await GC for recall.
So the question is: any consideration I could take to have it play without those outofmemories? Or is it bug and should I fix it by sideloading and playing with your project?

**Comment by higankanshi** [comment]
how many vlcplayer have you used?

**Comment by Nikolas-LFDesigns** [comment]
3 at max, one (the one I have troubles with) for video, one is music-only, one is created periodically for audio clip. Those two are created with false in constructor.

**Comment by higankanshi** [comment]
Have you seen the memory usage?

**Comment by Nikolas-LFDesigns** [comment]
I can't, it happens mostly at night. On my brief test it grows with each video, cleaning up after some time, but InteropBitmap is the only one, Vlc, LibVlc are always 2 (or 1, or 3, depending on the currently playing content). So nothing exceeds its boundaries.
I have seen however, that memory usage is like a saw in a long term (guess it's because my test PC don't have a video card, so it's pushing a frame to the RAM), but not exceeds a border of 1 GB (on error it has cleaned up, so no numbers here ;[ ).

**Comment by higankanshi** [comment]
I think you can use "--no-audio" option to disable audio of first vlc player, and "--no-video" option to disable video of other players. Maybe it can save some memory.

**Comment by Nikolas-LFDesigns** [comment]
So, okay, I've got it: you have to reuse the same player to achieve stable playback (at least components count on memory dump didn't grow so drammatically video after video).
Leaving this open as there should be a way to completely dispose all libs and start over.
