### ISSUE TITLE
How to rotate the video ???

### ISSUE THREAD

**Issue by rmorejon** [higankanshi/Meta.Vlc#141]
In VLC.DotNet 

   myVlcControl.VlcMediaplayerOptions = new[] { "--quiet",
                                                          "--video-filter=transform",
                                                          "--transform-type=90"
                                                        };

**Comment by higankanshi** [comment]
You can use those options in Meta.Vlc too.
Or you can set the Transform property of VlcPlayer to do it easy.

**Comment by rmorejon** [comment]
My idea is to use any plugin VLC
