### ISSUE TITLE
Reload instance with different options set

### ISSUE THREAD

**Issue by maximality** [higankanshi/Meta.Vlc#143]
Hello.
In my app I need to reload vlc with different demux options. I create VlcPlayer in XAML. If i try to reload it with `vlcControl.Initialize(@"..\..\..\LibVlc", new[] { "-I", "dummy", "--verbose=0", "--quiet", "--overlay", "--video-filter=deinterlace", "--deinterlace=-1", "--avcodec-hw=any", "--avcodec-skiploopfilter=4", "--avcodec-fast" });
`
I get an exception "VlcPlayer is been inititialized".
How can I reload (reinitialize) this VlcPlayer instance with different options (different from AssemblyInfo.cs)? LoadMediaWithOptions don't work for me.

**Comment by higankanshi** [comment]
The `VlcPlayer.CreateMode` maybe can help you.

**Comment by maximality** [comment]
How can I handle (create and delete) multiple instances of VLC in the same VlcPlayer object in my XAML?

**Comment by higankanshi** [comment]
No, you can't do that, one player with one VLC instance
