### ISSUE TITLE
DisplayThreadDispatcher is Garbage Collected

### ISSUE THREAD

**Issue by abdul2000** [higankanshi/Meta.Vlc#145]
Hi,

I am trying to use the VlcControl without XAML. It works but sometimes randomly it will through InvalidOperationException with message:

"VlcPlayer not be ready, if you want to use VlcPlay no in XAML, please read this Wiki: \"https://github.com/higankanshi/Meta.Vlc/wiki/Use-VlcPlayer-with-other-controls\".

I need to load the control into the view tree programmatically through the C# code. And I followed the wiki article.

Can you please help?

**Comment by higankanshi** [comment]
You need use `VlcPlayer(Dispatcher customDisplayThreadDispatcher)` and `VlcPlayer(bool displayWithThreadSeparatedImage)` in CS code.
Which constructor did you use?

Can you give me your code which initialize the VlcPlayer.
