### ISSUE TITLE
How to get list the next frame data ??

### ISSUE THREAD

**Issue by rmorejon** [higankanshi/Meta.Vlc#146]
I need to get the frames in a time interval.

            this.Player.PauseOrResume();
            float aPosition = this.Player.Position;
            List<float> listPosition = new List<float>();
            List<Image> listImg = new List<Image>();

             this.Player.DisplayThreadDispatcher.BeginInvoke(
                DispatcherPriority.Normal,
                new Action(
                    () =>
                        {
                            for (int i = 0; i < 20; i++)
                            {
                                Image img = new Image();

                                if (this.Player.VideoSource != null)
                                {
                                    img.Source = this.Player.VideoSource.Clone();
                                    var time= TimePositions(aPosition);
                                    aPosition = this.PositionTime(TimeSpan.FromSeconds(tiempo.TotalSeconds + 1.0));
                                    if (aPosition < 1)
                                    {
                                        this.Player.Position = aPosition;
                                        Thread.Sleep(150);
                                    }
                                    listImg.Add(img);
                                    listPosition.Add(aPosition);

                                    Thread.Sleep(150); //dormir este proceso durante 200ms
                                }
                            }
                        }));

no working ..., in Vlc.DotNet worked

**Comment by higankanshi** [comment]
If you need to get Images which can render to your UI thread.
Please read this wiki [Use VlcPlayer with other controls](https://github.com/higankanshi/Meta.Vlc/wiki/Use-VlcPlayer-with-other-controls). You need initialize VlcPlayer in CS code with `var player = new VlcPlayer(false);`.
