### ISSUE TITLE
Unsure About Error Origin

### ISSUE THREAD

**Issue by ITr1ckst3rI** [higankanshi/Meta.Vlc#147]
Exception Info: System.NullReferenceException
   at Meta.Vlc.Wpf.VlcPlayer.VideoDisplayCallback(IntPtr, IntPtr)

Seems like this error is being thrown from my app, but i cannot trace it back. That is the full stacktrace as well..

Any Idea where this could be stemming from?

**Comment by higankanshi** [comment]
You can include those project to your solution. Then you can get more information  about it.

**Comment by ITr1ckst3rI** [comment]
Thanks for the reply :)

I will try to do that. In case I can't figure it out on my own, can you give a quick run down on how to do so?

This is the last bug I have with my project, looking forward to resolving it

**Comment by higankanshi** [comment]
Just clone it and add it to your solution in VS, then in add the reference of Meta.Vlc to your project.

**Comment by jasondavidcarr** [comment]
Hi IT, I've had a similar issue and was able to mostly resolve it by adding this code to the top of the VideoDisplayCallback method in VlcPlayer.Events.cs.

`            if (_context == null || DisplayThreadDispatcher == null)
            {
                return;
            }`

What is happening is that if the loaded VLC player isn't displayed on the screen at the time (or at least that's what it seems to me), you get that error. I have another ticket in here and I'm hoping I can work with higankanshi to resolve it. There are also similar issues hiding videos after they've started playing and related things like that.

**Comment by higankanshi** [comment]
Check the last commit the issue have been fixed.
