### ISSUE TITLE
TabControl

### ISSUE THREAD

**Issue by olezhko** [higankanshi/Meta.Vlc#149]
After return to tabItem with video, video is not playing, only black screen.

**Comment by higankanshi** [comment]
Are you using nuget package?
Maybe you can try the GitHub version of it, at Jul 9 commit(32fa8d74e840fe4a4dcad57630d9953b095d3dea) I fix VlcPlayer can't unload and reload, but we have no test about it, maybe you can help us to test it.

**Comment by jasondavidcarr** [comment]
Hi higankanshi, I can confirm that that commit fixed a lot of those similar issues regarding unloading, reloading, hiding, showing, etc. However there are still a few issues that remain; please see ticket #150. I really appreciate your work here and any help you can provide.

**Comment by higankanshi** [comment]
Check the last commit, I think this issue have been fixed.
