### ISSUE TITLE
More Exceptions - Continuation

### ISSUE THREAD

**Issue by jasondavidcarr** [higankanshi/Meta.Vlc#151]
Hello again higankanshi, we are indeed a lot closer but unfortunately we are still running into some of the same issues. There are still three exceptions that I am seeing:

System.InvalidOperationException: VlcPlayer not be ready, if you want to use VlcPlay no in XAML, please read this Wiki: "https://github.com/higankanshi/Meta.Vlc/wiki/Use-VlcPlayer-with-other-controls".
   at (VlcPlayer , IntPtr& , UInt32& , UInt32& , UInt32& , UInt32& , UInt32& )
   at Meta.Vlc.Wpf.VlcPlayer.VideoFormatCallback(IntPtr& opaque, UInt32& chroma, UInt32& width, UInt32& height, UInt32& pitches, UInt32& lines)

System.NullReferenceException: Object reference not set to an instance of an object.
   at (VlcPlayer , IntPtr , IntPtr& )
   at Meta.Vlc.Wpf.VlcPlayer.VideoLockCallback(IntPtr opaque, IntPtr& planes)

System.NullReferenceException: Object reference not set to an instance of an object.
   at (VlcPlayer , IntPtr , IntPtr )
   at Meta.Vlc.Wpf.VlcPlayer.VideoDisplayCallback(IntPtr opaque, IntPtr picture)

These exceptions are occurring much less often since the last changes, but they are unfortunately still occurring. We are also seeing occasional instances where the videos do not display and of course do not play.

In the VideoDisplayCallback method, I am still very rarely seeing that NullReferenceException despite the fact that we're checking for NULL on _content and DisplayThreadDispatcher. I've tried checking for NULL on VideoSource too but it didn't make any difference. I also tried checking inside of the invoke as well just to see if it was a timing issue, and it may have improved it but it did not fix it 100%. For the life of me I cannot figure out what variable is causing the null reference issue, so for now I'm just catching it in a try catch.

As mentioned we're also seeing a similar null reference exception in the VideoLockCallback method. I added a line at the top to return IntPtr.Zero if VlcMediaPlayer or _context are NULL. However, I have no idea if this is any sort of a proper fix. It may also be part of the cause of the non-playing videos.

Then in the VideoFormatCallback method, I am still seeing the InvalidOperationException. For now I'm simply returning 0 instead of throwing that exception when DisplayThreadDispatcher is NULL. Again, of course I doubt this is a proper fix.

From what I can tell so far, the above changes are at least eliminating the exceptions and crashes. However, we're still seeing instances where the videos do not play; on my system it's happening around 5% of the time.

Again, thank you once again for all your work on this. I would put in a change request but I'm not really confident in any of these changes, so I don't think that would be wise. Also, I am using this in a commercial product so I would like to pay you for your time if you'd be willing to work with us to get this stuff all the way fixed. :)

Thanks,
Jason

**Comment by jasondavidcarr** [comment]
By the way, if you'd like to discuss anything in private, you can email me at jasondavidcarr@gmail.com. Thanks again higankanshi.

**Comment by ITr1ckst3rI** [comment]
Just wanted to chime in here and say thanks jason for tackling these issues. I have had very infrequent but similar issues with the application I am building. Hopefully you and higankanshi can nail these problems for good. I know i am not helping, but I wanted to show my thanks for helping me with my other ticket.

Also, thanks higankanshi for this wrapper. It's really awesome to use over the VLC.NET wrapper. Keep up the good work, it IS appreciated!

**Comment by jasondavidcarr** [comment]
No problem IT, but really higankanshi is the person to thank here. I'm just a stumbling idiot when it comes to this codebase. :P

**Comment by iccome** [comment]
I also met these issues,  so I merge the latest version,  when reach the end of the video, I try to play the next video, but the screen is still, and the audio is playing, 
I play the next video with this code:
 Player.RebuildPlayer();
Player.LoadMedia(uri);
 Player.Play();
