### ISSUE TITLE
Adjust the video filter "hue" no working

### ISSUE THREAD

**Issue by rmorejon** [higankanshi/Meta.Vlc#154]

**Comment by higankanshi** [comment]
Which version of vlc you have used.

**Comment by rmorejon** [comment]
I am using the version that is in the code Meta.VLC

**Comment by rmorejon** [comment]
I am using the version that is in the code Meta.VLC

**Comment by higankanshi** [comment]
Have you set VlcMediaPlayer.IsAdjustEnable to true?

**Comment by rmorejon** [comment]
yess
I work brightness, constrast, the only one that does not work is hue
