### ISSUE TITLE
VisualBrush from VlcPlayer WPF control

### ISSUE THREAD

**Issue by fabianPas** [higankanshi/Meta.Vlc#155]
How do I create a VisualBrush using the WPF VlcPlayer control? When I call new VisualBrush(vlcPlayer), I get an exception that is not really descriptive; it says VlcPlayer is been initialized. It is, and it should be, right? Shouldn't it work if the VlcPlayer is a proper WPF control right?

**Comment by higankanshi** [comment]
If you want to get frame data, VlcPlayer.VideoSource property is recommend.

**Comment by fabianPas** [comment]
How does one convert a VideoSource to a proper VisualBrush as it is a BitmapSource? I want to use the VisualBrush to render multiple video player to a canvas.

**Comment by higankanshi** [comment]
You can use the Image control, and set the VideoSource to Image.Source, then create a VisualBrush with `new VisualBrush(image)`.
If you want to render video with Image, please read this wiki:
https://github.com/higankanshi/Meta.Vlc/wiki/Use-VlcPlayer-with-other-controls

**Comment by fabianPas** [comment]
But why do I get a threading error even though the dispatcher is used and the image is created on the same thread?                                                                                                                                                                                                                From: HIGANSent: Tuesday, 13 September 2016 15:11To: higankanshi/Meta.VlcReply To: higankanshi/Meta.VlcCc: Fabian Pas; AuthorSubject: Re: [higankanshi/Meta.Vlc] VisualBrush from VlcPlayer WPF control (#155)You can use the Image control, and set the VideoSource to Image.Source, then create a VisualBrush with new VisualBrush(image).
If you want to render video with Image, please read this wiki:
https://github.com/higankanshi/Meta.Vlc/wiki/Use-VlcPlayer-with-other-controls

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/higankanshi/Meta.Vlc","title":"higankanshi/Meta.Vlc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/higankanshi/Meta.Vlc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@higankanshi in #155: You can use the Image control, and set the VideoSource to Image.Source, then create a VisualBrush with `new VisualBrush(image)`.\r\nIf you want to render video with Image, please read this wiki:\r\nhttps://github.com/higankanshi/Meta.Vlc/wiki/Use-VlcPlayer-with-other-controls"}],"action":{"name":"View Issue","url":"https://github.com/higankanshi/Meta.Vlc/issues/155#issuecomment-246675918"}}}

**Comment by fabianPas** [comment]
Your soluction indead worked. I changed the dispatching and it is correctly functioning now.

SOLVED!
