### ISSUE TITLE
Question: Nuget Packages

### ISSUE THREAD

**Issue by 9Arca9** [higankanshi/Meta.Vlc#157]
Have the Nuget Packages been updated with your #151 fixes?

**Comment by higankanshi** [comment]
We will update it later.

**Comment by 9Arca9** [comment]
Any updates on this?

Additionally, is there a way to change the video source without waiting (sometimes up to 20-30 seconds) for the video player to full stop?

**Comment by higankanshi** [comment]
Now I don't have the sign key file.
We will update it in next month.

**Comment by higankanshi** [comment]
Updated.
