### ISSUE TITLE
Feature: Serializable Object

### ISSUE THREAD

**Issue by 9Arca9** [higankanshi/Meta.Vlc#162]
Was wondering if we can make the VLCPlayer class serialize so i can deep clone the player in code. This would allow me to use the player in a quicker manner than what is possible now.

**Comment by higankanshi** [comment]
Got it.
Working on it.

**Comment by 9Arca9** [comment]
Awesome, thank you!

**Comment by 9Arca9** [comment]
Any updates?

**Comment by higankanshi** [comment]
I have build a VlcPlayerSettings class, to make the VlcPlayer serializable.
But I found there are many problem with, it not work fine.
Some properties need be set in a different time.

**Comment by 9Arca9** [comment]
Thanks for the update! 

understandable. things don't always go as smoothly as one would like.
