### ISSUE TITLE
Taking a snapshot throws an exception

### ISSUE THREAD

**Issue by tinowild** [higankanshi/Meta.Vlc#163]
Calling the TakeSnapshot Method causes an InvalidOperationException, with the additional Information: The calling thread cannot access this object because a different thread owns it.

**Comment by kozubik** [comment]
I was getting this exception too with NuGet packages, but in the latest code taking snapshots works (with no changes in my code)

`            if (!Directory.Exists("snapshots"))
                Directory.CreateDirectory("snapshots");

            VlcInst.TakeSnapshot("snapshots", SnapshotFormat.JPG, 100);`

**Comment by higankanshi** [comment]
I will update the nuget package in next month.
I have no the sign key file now.
