### ISSUE TITLE
Recreating Window causes NullPointerException

### ISSUE THREAD

**Issue by kozubik** [higankanshi/Meta.Vlc#164]
If you attempt to create another instance of the MainWindow from provided WPF sample after closing the previous one, the app will crash, because the ApiManager.DefaultVlc is disposed and pointer is null (because of ApiManager.ReleaseAll(); in window closing event).

First creation: 

VlcPlayer.Initialize assigns ApiManager.DefaultVlc and calls it's method Vlc.CreateMediaPlayer() that passes reference to Vlc itself (Vlc itself is valid)

Second creation:

VlcPlayer.Initialize assigns Apimanager.DefaultVlc and calls it's method Vlc.CreateMediaPlayer() that passes reference to Vlc itself (Vlc is not valid because _disposed==true and InstancePointer==IntPtr.Zero which causes NullReferenceException)

Recreation:
create separated project with reference to one of the sample project (i used .net4.0) and use this main:

``` CSharp
        [STAThread]
        private static void Main(string[] args)
        {
            for (;;)
            {
                Meta.Vlc.Wpf.Sample.MainWindow x = new MainWindow();

                x.ShowDialog();

                x.Close();

                x = null;
            }
        }
```

WorkAround:
commenting out line ApiManager.ReleaseAll(); in closing event or editing switch in VlcPlayer.cs:

``` CSharp
            switch (CreateMode)
            {
                case PlayerCreateMode.NewVlcInstance:
                    Vlc = new Vlc(libVlcOption);
                    ApiManager.Vlcs.Add(Vlc);
                    break;

                case PlayerCreateMode.Default:
                default:
                    Vlc = ApiManager.DefaultVlc;

//added code
                    if (Vlc.InstancePointer == IntPtr.Zero)
                    {
                        Vlc = new Vlc(libVlcOption);
                        ApiManager.Vlcs.Add(Vlc);
                    }
//
                    break;
            }
```

Please let me know if i am doing something wrong or if that's a bug.

**Comment by higankanshi** [comment]
ApiManager.ReleaseAll() method only be called when your application is closing.
If a window which contain a VlcPlayer will be closed, but your application don't end, you should not to call ApiManager.ReleaseAll().

You can remove the ApiManager.ReleaseAll() calling from MainWindow closing event to fix it.
Your change is not best way to fix this issue.
