### ISSUE TITLE
Sample code run on windows 7 Service Pack 1 will crash

### ISSUE THREAD

**Issue by kingeaglewang** [higankanshi/Meta.Vlc#165]
I download the sample code from GitHub.
I run the code without any modification.
I run on .net 4.5.

I load one video, and it start to play the video.
And then, I load another video, and it will crash.

The visual studio show there is a System.AccessViolationException in Meta.Vlc.dll
The visual studio stops and point at the following set function in VlcMediaPlayer.cs.

 public VlcMedia Media
        {
            get
            {
                return InstancePointer == IntPtr.Zero
                    ? null
                    : HandleManager.GetVlcObject(_getMediaFunction.Delegate(InstancePointer)) as VlcMedia;
            }
            set { _setMediaFunction.Delegate(InstancePointer, value == null ? IntPtr.Zero : value.InstancePointer); }
        }

Is there any idea about this crash issue?
Thanks.

**Comment by higankanshi** [comment]
See #95 .
Windows7 maybe has some error with vlc.

But @mcolleoni has give some idea to fix it, you can have a try.

**Comment by kingeaglewang** [comment]
Thanks. It seems to work normally.

**Comment by higankanshi** [comment]
If it worked, I will add pull it to master.

**Comment by kingeaglewang** [comment]
I have try mcolleoni method on both windows 7 and windows 10.  Both work fine.

**Comment by higankanshi** [comment]
Thanks for your test.
