### ISSUE TITLE
Current frame when rendering with xaml.

### ISSUE THREAD

**Issue by nasirovsh** [higankanshi/Meta.Vlc#169]
Is it possible to get current playing frame when vlcplayer created in default xaml mode ?

**Comment by higankanshi** [comment]
what kind of frame data do you want?
pixel data? or image source?

**Comment by nasirovsh** [comment]
I need pixel data. Will send it to EmguCV Mat/Image for further processing.

**Comment by higankanshi** [comment]
Not yet, but we can support it maybe, I'm not sure we have the write permission for the surface.
If we have the permission, we can do this.

**Comment by nasirovsh** [comment]
Can there be some workaround to copy BitmapSource VideoSource from VlcPlayer thread to main thread ?

**Comment by nasirovsh** [comment]
Why need write permission. You mean to write directly onto surface object from vlcplayer thread ? Sorry for naive questions ))

**Comment by higankanshi** [comment]
Why do you want to BitmapSource in main thread?

**Comment by nasirovsh** [comment]
I was thinking to receive frame image in main thread and pass it to image processing method. 
How do you think it can be acquired, what is the best way ? Not necessarily bitmapsource just System.Drawing.Bitmap is better.

**Comment by nasirovsh** [comment]
I found solution. I just get reference to Vlc.VideoSource  and convert it to Emgu Image through VideoSource  belonging thread dispatcher. Since Emgu Image is created in main thread I can use it to send to another library for processing operation
 `              BitmapSource bmpVidSrc;
                bmpVidSrc = VlcPlayer.VideoSource;
                bmpVidSrc.Dispatcher.Invoke(() =>
                {
                    var image = bmpVidSrc;
                    BitmapEncoder bmpEncoder = new BmpBitmapEncoder();
                    BitmapFrame bmpFrame = BitmapFrame.Create(image);
                    bmpEncoder.Frames.Add(bmpFrame);
                    MemoryStream ms = new MemoryStream();
                    bmpEncoder.Save(ms);
                    Bitmap bmp = new Bitmap(ms);

                    try
                    {
                        imgFrame = new Image<Bgr, byte>(bmp);
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e.Message);
                        return;
                    }
                    ms.Dispose();                    
                    DeleteObject(bmp.GetHbitmap());  
                });`

**Comment by nasirovsh** [comment]
Thanks for hints
