### ISSUE TITLE
InvalidOperationException when trying to play Video

### ISSUE THREAD

**Issue by DininduInduwara** [higankanshi/Meta.Vlc#171]
I am trying to use the VlcControl without XAML but through C# only. 
The WPF code for Image control is:
`<Image Name="ImageControl" Width="854" Height="480"/>`

And the C# code is:
```
public MainWindow()
{
      InitializeComponent();

      var player = new VlcPlayer(ImageControl.Dispatcher);

      player.Initialize(@"D:\Code Repository\MetaVLC\MetaVLC\bin\Debug\LibVlc","-I", "dummy", "--ignore-config", "--no-video-title");
            
      ImageControl.Source = player.VideoSource;
      player.VideoSourceChanged += (o, args) =>
      {
           ImageControl.Source = args.NewVideoSource;  //Error thrown here
      };
      player.LoadMedia(@"D:\ffmpeg\jwa.mp4");
      player.Play();
}
```

But it keeps on throwing an InvalidOperationException occured in WindowsBase.dll.

Error:
`System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=The calling thread cannot access this object because a different thread owns it.
  Source=WindowsBase
  StackTrace:
       at System.Windows.Threading.Dispatcher.VerifyAccess()
       at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
       at System.Windows.Controls.Image.set_Source(ImageSource value)
       at MetaVLC.MainWindow.<.ctor>b__0_0(Object o, VideoSourceChangedEventArgs args) in D:\Code Repository\MetaVLC\MetaVLC\MainWindow.xaml.cs:line 37
       at Meta.Vlc.Wpf.VlcPlayer.set_VideoSource(BitmapSource value)
       at Meta.Vlc.Wpf.VlcPlayer.VideoLockCallback(IntPtr opaque, IntPtr& planes)
  InnerException: 
`
Maybe running it on a different thread might solve it. But how to create a ThreadSeparatedImage control? I looked at the tutorial, but it doesnt show how to make a the ThreadSeparatedImage Contro itself.

**Comment by higankanshi** [comment]
Try this:
```CSharp
player.VideoSourceChanged += (o, args) =>
{
    DisplayImage.Dispatcher.BeginInvoke(new Action(() =>
    {
        ImageControl.Source = args.NewVideoSource;
    }));
};
```

**Comment by DininduInduwara** [comment]
Okay, that seems to work. Also what is the point of implementing a ThreadSeperatedImage control?

**Comment by higankanshi** [comment]
ThreadSeperatedImage can host the image control in a independent thread, if your application UI has been blocked, video will not be blocked, it will playback continue.

Reset buffer? What it mean?

**Comment by DininduInduwara** [comment]
Oh okay. That makes sense. Thank you.

And when it comes to resetting the buffer, this is the problem.
I am downloading a video in chunks of 5mB. When the first chunk is complete, the VlcControl starts playing the video while the download continues. The problem is that at random timecodes stuttering/freezing occurs. I think this is because Vlc has already buffered that part of the video before it had finished downloading.

So I was wondering if I could force VLC to reset the buffer so that this wouldnt occur. It is not a problem with the video itself. I have checked.

[Screenshot](https://i.stack.imgur.com/DbCz2.jpg)

**Comment by higankanshi** [comment]
ummm, no idea with it, maybe you can to open a issue for vlc
