### ISSUE TITLE
Use of Meta.Vlc (including VlcPlayer and ThreadSeparatedImage) in a MVVM model.

### ISSUE THREAD

**Issue by Tchebourachka** [higankanshi/Meta.Vlc#175]
Hello

As a novice in the WPF world, I have a question about ThreadSeparatedImage and VlcPlayer classes.
I'm currently developing a C#/WPF application following an MVVM pattern.

I use a "ThreadSeparatedImage element" in my XAML file, element which I want to associate to a "VlcPlayer". 

I would like to know if it is possible to bind a source for ThreadSeparatedImage to stay in a strict MVVM model. I have read the tutorial about other controls, but I do not see how to configure the XAML part.

Thanks a lot.

**Comment by higankanshi** [comment]
Just create a VlcPlayer with 'new VlcPlayer(true)', and get the VlcPlayer.VideoSource and set it to ThreadSeparatedImage.Source.
You can listen the VlcPlayer.SourceChanged event, reset the Source when VideoSource changed.

**Comment by Tchebourachka** [comment]
Thanks for you answer.

But if the "ThreadSeparatedImage " is defined in a XAML file ("view" of my MVVM), is it possible to link it to a  VlcPlayer.VideoSource  of a VlcPlayer created in a ViewModel file? 
`<vlc:ThreadSeparatedImage x:Name="videoSource" Source={Binding Path=ImageSource}" />`

Something like that in the .cs file:
```
var player = new VlcPlayer(true); 
...
player.Initialize(vlcPath);
ImageSource.Source = player.VideoSource;

player.VideoSourceChanged += (o, args) =>
{
    ImageSource.Source = args.NewVideoSource; 
};
```

**Comment by higankanshi** [comment]
Yes, of course

**Comment by eddium** [comment]
The compiler just complains that `Source` is not a dependency property in the code given above. Is there any approach without changing your library that could smoothly adapt to the MVVM model?
