### ISSUE TITLE
Not able to play mp3+cdg files

### ISSUE THREAD

**Issue by anhlunnhaque** [higankanshi/Meta.Vlc#177]
Hi,

I was able to play mp3+cdg files in your old project before you change to Meta. In the old project. It was able to play .mp3 and it reads .cdg as 'external sub'. I've attach a test file. Download, change extension to zip and extract.

Thanks.
![cb20205-11 - christmas carol - skip ewing zip](https://cloud.githubusercontent.com/assets/16323974/22046318/6a0a0b08-dce5-11e6-940f-b1b6f038406a.png)

**Comment by higankanshi** [comment]
See:
#108

**Comment by anhlunnhaque** [comment]
Ahh.. I forgot. Thanks.
