### ISSUE TITLE
Dump stream to file

### ISSUE THREAD

**Issue by jalcaine** [higankanshi/Meta.Vlc#182]
Hello,
I`m trying to dump  network stream video to a file. I add the options in the player

            Player.AddOption("--demux=dump");
            Player.AddOption("--demuxdump-file backup.ts"); 

but not make the file. 

I try to add the option in the AssemblyInfo.cs like:

[assembly: VlcSettings(@"libvlc", "-I", "--dummy-quiet", "--ignore-config", "--no-video-title", "--no-sub-autodetect-file", "--rtsp-tcp", "--file-logging", "--logfile=log.txt", "--demux=dump","--demux-dump-file c:/backup.ts")]
but then a Exception is thrown " Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll"

Is possible to dump a stream ? How?
Thanks,

**Comment by higankanshi** [comment]
Maybe you can try ':demux=dump' in load media method

**Comment by jalcaine** [comment]
The LoadMedia method, only accept one parameter. How I can add :demux=dump in load media? 
For example:
vlcPlayer.LoadMedia(new Uri("http://127.0.0.1"));
Thanks

**Comment by higankanshi** [comment]
You can try `VlcPlayer.LoadMediaWithOptions(string, params string[])`.
