### ISSUE TITLE
Nuget contains only x86 build

### ISSUE THREAD

**Issue by Sergey-Terekhin** [higankanshi/Meta.Vlc#185]
Hello
I try to create vlc-based video player, but I have requrement to be architecture-independent (I mean x86 or x64)
But Nuget package provided contains only x86 build of libraries, so it is impossible to use without fork and recompilation

Is it possible to provide AnyCPU build in the Nuget package?

Initialization of VLC libraries will be something like that:
```C#
var path =IntPtr.Size == 8 ? "x64" : "x86";
Meta.Vlc.Wpf.ApiManager.Initialize(path);
```

Thanks for your job!

**Comment by higankanshi** [comment]
I think there are x64 version of Meta.Vlc ans Meta.Vlc.Wpf on Nuget.
But we only have x86 version of Meta.Vlc.Lib.
You need to compilation libvlc by yourself.

See:
https://github.com/higankanshi/Meta.Vlc/wiki/Compile-VLC-for-xZune.Vlc

**Comment by Sergey-Terekhin** [comment]
It is possible to get both versions of vlclib from vlc player installation (x86 and x64)
I've tested AnyCPU solution in my custom build of Meta.Vlc. The only change I made - I changed from x86 to AnyCpu in the solution configuration :)
And manage two versions (x86 and x64) of libraries in project's referenses is great pain...

**Comment by timevision** [comment]
Can someone build the x64 version of the libVLC and share? With the expansion code for the DVD menu?
