### ISSUE TITLE
How to specify filename for snapshot?

### ISSUE THREAD

**Issue by Sergey-Terekhin** [higankanshi/Meta.Vlc#187]
Hello!
I try to make snapshot form VlcPlayer, but it is impossible to specify concrete filename - only dir.
May be it would be better if user could specify full path including filename, not only directory?

**Comment by higankanshi** [comment]
Check the last commit
a2451b9987a75e15210866242066776fecc33e19

You can specify filename for snapshot with `VlcPlayer.TakeSnapshot(string, int = 100)`

**Comment by Sergey-Terekhin** [comment]
May be it would be better return ImageSource (or BitmapSource) to the user and allow him to deside that to do - save to disk, database, Twitter etc.?

**Comment by higankanshi** [comment]
You can get the `VlcPlayer.VideoSource` to do what you want

**Comment by Sergey-Terekhin** [comment]
Ok, Thank you!
