### ISSUE TITLE
Problem with players that are initialized inside page view that are not showed in screen.

### ISSUE THREAD

**Issue by ThanhND825** [higankanshi/Meta.Vlc#189]
Hi there,

I'm using your library for a monitoring application. We have list of about 40 cameras.
The application will display 4 camera in at the same time and have to display new cameras each 30 seconds automatically. 
We don't want to have delay between transition so we decide to load 4 more cameras for next page. These cameras are loaded to another view and is not display in the screen until the time come. But the problem is the player is initialized successfully. We got the message ("Initialize Video Content : 352x290"). But when we show the new page view using animation, the players are not displayed.(We use ThicknessAnimation for margin to implement transition effect)
If we change the time duration to 3 seconds, the new page is showed before the players are loaded successfully. The players will be display.
We use 4x4 Grid (2 columns and 2 rows) to hold players, and set player.Stretch to Stretch.Fill.
Is there anyway/example to make work?

Thank you.

**Comment by ThanhND825** [comment]
One more thing,
If we stop and play the view again after showing the page view, new players will display.

**Comment by higankanshi** [comment]
Check the `VlcPlayer.VideoSource` property, is it null when you load next page?

**Comment by ThanhND825** [comment]
Thank you for your quick response. 

I checked the `VlcPlayer.VideoSource`. It is null when initialized players that are not inside current view.
Although we have call `LoadMedia(new Uri(streamURL))` before trigger initialization. `streamURL` is OK and there are no exception triggered. I also check context and see that the context is also null when the players is not in current view.
But if I stop and play it again, VideoSource is set. Could you please tell me what should I do next? Due to security policy, I can not upload the source code here. :(

**Comment by higankanshi** [comment]
Got it, I will try to fix this issue...

**Comment by ThanhND825** [comment]
Thank you 👍

**Comment by ThanhND825** [comment]
I find away to make it. Thank you :)
