### ISSUE TITLE
Subtitles are found but cannot be selected

### ISSUE THREAD

**Issue by Kempeth** [higankanshi/Meta.Vlc#191]
I'm trying to display subtitles. After some digging I've found these Properties:

VlcPlayer.VlcMediaPlayer.Subtitle
VlcPlayer.VlcMediaPlayer.SubtitleCount
VlcPlayer.VlcMediaPlayer.SubtitleDescription

SubtitleCount shows me I have 11 Subtitle Tracks which matches what VLC shows when I open the file there. However when I set the Subtitle property to any value it stays at -1 (for deactivated).

**Comment by LarsWesselius** [comment]
What you *could* try is setting it manually through libvlc.
```
[DllImport("lib/libvlc.dll", CallingConvention = CallingConvention.Cdecl)]
public static extern int libvlc_video_set_spu(IntPtr mp, int spu);
```

Then call it as such;

`
int result = libvlc_video_set_spu(myVlcMediaPlayerInstance.InstancePointer, 1);
`
and have a look at the result. Documentation for this function can be found here; https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__video.html#gac0594ad8db60a38a19eca5858f087e9d
