### ISSUE TITLE
Doesn't work as of 2017

### ISSUE THREAD

**Issue by masiton** [higankanshi/Meta.Vlc#195]
Has useless documentation, straight up doesn't work, upon downloading from package manager and putting into WPF project fails with exception that only contains asian characters. Don't bother, save yourself some time and find different dll.

**Comment by DannyGlover** [comment]
It does work, it just requires adding LibVLC. I.e. the VLC media player and its plugins

**Comment by LarsWesselius** [comment]
Not very constructive, been using this library for a while now and it's working great. Be sure to get the Meta.Vlc.Lib package as well, although it should do that automatically.
