### ISSUE TITLE
EndBehavior Repeat not repeating the video

### ISSUE THREAD

**Issue by rlbryan** [higankanshi/Meta.Vlc#197]
I have this code on playing a video from a local filepath

            Player.LoadMedia(new Uri(filePath));
            Player.EndBehavior = EndBehavior.Repeat;
            Player.Play();

It's playing the video but It does not loop the video.

Is there some kind of additional initialization that I need to set for it to work?

xaml code:
<wpf:VlcPlayer x:Name="Player" LibVlcPath="..\..\libvlc" EndBehavior="Repeat" Stretch="Fill"/>

**Comment by higankanshi** [comment]
Sample work fine with my PC...
Can you provide more information about it?
