### ISSUE TITLE
如何播放Stream？或给VLC添加Cookie？

### ISSUE THREAD

**Issue by 944095635** [higankanshi/Meta.Vlc#200]
播放Stream？给VLC添加Cookie？

我现在拿到一个Http:///www.xxxxx.com/getVideo.aspx?id=4444444

对方服务器验证cookie " user = 123 才会返回一个mp4的地址》

我无法给 vlc添加cookie。我自己尝试本地http请求到stream 。但是无法用vlc 播放stream。

**Comment by Harris-wu** [comment]
你先用http协议请求 拿到真实地址 才给播放器去播呗

**Comment by 944095635** [comment]
这个地址好像已经是最终的地址了。我尝试了一下 好像失败了。
视频地址：http://xfcd.ctfs.ftn.qq.com/ftn_handler/c38e9c9c9ead1155a167aa6c9eaaf8f22c7c25c60c49b504cded7979b40a0f61570e7028c76404fac45ca814e186221895bb8e102932c05703e89e2946cfaae9/?fname=player.mp4

Cookie:
FTN5K=531038f8

**Comment by higankanshi** [comment]
感觉这种东西应该是通过 --http-cookies 这种参数去干的...我是指猜的...vlc 的参数太多了，很多功能都要靠参数...OTZ
