### ISSUE TITLE
HLS duration is not returned properly

### ISSUE THREAD

**Issue by northpaul** [higankanshi/Meta.Vlc#202]
When I open any HLS stream, VlcPlayer.VlcMediaPlayer.Length is 0. Even when MediaEnded is fired, the duration is still 0. If I play it again once the stream finished playing the first time, the duration is returned, but the video plays back white and the audio is silent. Same with the current position VlcPlayer.Time.TotalMilliseconds.

**Comment by higankanshi** [comment]
I think this is a problem of vlc, libvlc can't get information of stream media.
