### ISSUE TITLE
Can you provide more samples?

### ISSUE THREAD

**Issue by testniracun** [higankanshi/Meta.Vlc#209]
Can you provide sample how to connect to AXIS IP camera? 
And how to restream video from port 8554?

Sample provided don't compile, so can you make some more? 
I'm using VS2015

**Comment by higankanshi** [comment]
Sample work fine...VS2015 too.
I think you can go to the [The VideoLAN Forums](https://forum.videolan.org/viewforum.php?f=32) and ask developer of VLC about playback a AXIS IP camera stream.
