### ISSUE TITLE
Updating NuGet Package

### ISSUE THREAD

**Issue by endercrest** [higankanshi/Meta.Vlc#210]
I have noticed that the NuGet package hasn't been update since Novemeber 19, 2016 but some fixes have since been added to the repository. Would we be able to get the NuGet package updated? As were are currently wanting to use the most recent changes, which aren't available.

It might also be helpful to include pdb files in the NuGet package to help with debugging.

**Comment by higankanshi** [comment]
I will update it in this month

**Comment by higankanshi** [comment]
Updated, check it.
