### ISSUE TITLE
AspectRatio probleme

### ISSUE THREAD

**Issue by SheppeR** [higankanshi/Meta.Vlc#219]
Hi i have a problem with the aspect ratio propertie, the player strech the windows size on resize

`
<Grid>
    <wpf:VlcPlayer 
            x:Name="Player"
            AspectRatio="_16_9"
            EndBehavior="Nothing"
            LibVlcPath="./LibVlc"
            VlcOption="{StaticResource VlcOptions}" />
</Grid>
`

**Comment by higankanshi** [comment]
Check the last commit f03c5c59f7a50b7c7b0e324d14f52daabddf198f
BTW, AspectRatio property only work on when Stretch property is not 'none'.

**Comment by SheppeR** [comment]
Thanks, will try the latest rev

**Comment by SheppeR** [comment]
Its look like ok for the aspect ratio but on resize the window, the is cut by the form, there is no black band on the player.
image preview with Stretch="None"
![prev1](https://user-images.githubusercontent.com/4973320/27446637-9f2e786e-577e-11e7-89a0-4790a81914ff.jpg)
![prev2](https://user-images.githubusercontent.com/4973320/27446638-9f31cce4-577e-11e7-931b-363239fe5bea.jpg)

**Comment by higankanshi** [comment]
You should set Stretch to 'Uniform'...

**Comment by SheppeR** [comment]
Its ok, sorry forgot to post a feedback, its work fine ;)
Thanks
