### ISSUE TITLE
error of memory?

### ISSUE THREAD

**Issue by xpachin** [higankanshi/Meta.Vlc#220]
hey man!
i am using WPF meta.vlc and i have a window with a grid with several wpf players from streaming cameras. the problem is that when i have more than 16 (mostly) cameras at the same time, the app crashes (even tough the cpu is on 40% and the memory only 600MB, is a very powerful computer).
 this is the line that throws the error.
please help me!

_Image =
                (InteropBitmap)
                    Imaging.CreateBitmapSourceFromMemorySection(FileMapping, Width, Height, PixelFormat, Stride, 0);
        }_

and this is the error code

		
		
		'System.Runtime.InteropServices.COMException' occurred in PresentationCore.dll
		
		Additional information: Not eough storage is avaible to process this command. (Excepción de HRESULT: 0x80070008)
		
		
		System.Runtime.InteropServices.COMException was unhandled'

  ErrorCode=-2147024888
  HResult=-2147024888
  Message=Not eough storage is avaible to process this command. (Excepción de HRESULT: 0x80070008)
  Source=PresentationCore
  StackTrace:
       en System.Windows.Interop.InteropBitmap..ctor(IntPtr section, Int32 pixelWidth, Int32 pixelHeight, PixelFormat format, Int32 stride, Int32 offset)
       en System.Windows.Interop.Imaging.CreateBitmapSourceFromMemorySection(IntPtr section, Int32 pixelWidth, Int32 pixelHeight, PixelFormat format, Int32 stride, Int32 offset)
       en Meta.Vlc.Wpf.VideoDisplayContext..ctor(Int32 width, Int32 height, ChromaType chroma)
       en Meta.Vlc.Wpf.VideoDisplayContext..ctor(UInt32 width, UInt32 height, ChromaType chroma)
       en Meta.Vlc.Wpf.VlcPlayer.<>c__DisplayClass126_0.<VideoFormatCallback>b__0()
       en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       en System.Windows.Threading.DispatcherOperation.InvokeImpl()
       en System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       en MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       en System.Windows.Threading.DispatcherOperation.Invoke()
       en System.Windows.Threading.Dispatcher.ProcessQueue()
       en System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       en System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       en MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       en MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       en System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       en System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       en System.Windows.Threading.Dispatcher.Run()
       en Meta.Vlc.Wpf.ThreadSeparatedImage.<>c.<get_CommonDispatcher>b__2_0()
       en System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       en System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by higankanshi** [comment]
Yes, you should not create too many VlcPlayer at same time...
VlcPlayer will create a decode and display buffer for each media...
16 videos will tack too much memory...
