### ISSUE TITLE
偶尔会出现的异常

### ISSUE THREAD

**Issue by wayne2006** [higankanshi/Meta.Vlc#221]
你好，我在使用的过程中，发现大概10%几率会出现一些异常，请看一下是什么问题。
这些异常都是在打开程序时出现。
我调用Meta.Vlc的代码很简单,如下：
``` c#
private void Window_Loaded(object sender, RoutedEventArgs e)
 {
         Uri u = new Uri("XXXXX/Video/TEST.flv", UriKind.Absolute);
         Player.LoadMedia(u);
         Player.Play();
 }
```
异常会有2种，随机出现：
1：
![image](https://user-images.githubusercontent.com/21210915/27505514-e2b6e8f4-58d3-11e7-90c7-521de9fd3a31.png)

2:
![image](https://user-images.githubusercontent.com/21210915/27505509-c4072de2-58d3-11e7-82cf-9349562759f1.png)

谢谢！

**Comment by higankanshi** [comment]
Vlc载入需要一定的时间，所以建议不要在窗口 loaded 就开始进行播放视频，最佳的实践方式就是为用户播放一个载入动画，然后稍等片刻，再开始播放

**Comment by wayne2006** [comment]
好的 ，非常感谢。
