### ISSUE TITLE
SnapshotContext , switch path extension missing dot

### ISSUE THREAD

**Issue by funwaywang** [higankanshi/Meta.Vlc#227]
as far as I know, the method **Path.GetExtensions** return value have a dot prefix, just like ".jpg". but the switch in the method lost the litter dot.

> public SnapshotContext(String path, int quality)
        {
            Path = System.IO.Path.GetDirectoryName(path).FormatPath();
            Name = System.IO.Path.GetFileName(path);
            switch (System.IO.Path.GetExtension(path).ToLower())
            {
                case "bmp":
                    Format = SnapshotFormat.BMP;
                    break;
                case "png":
                    Format = SnapshotFormat.PNG;
                    break;
                case "jpg":
                case "jpeg":
                    Format = SnapshotFormat.JPG;
                    break;
                default:
                    throw new ArgumentOutOfRangeException("path", @"Screenshot format must be 'bmp', 'jpg' or 'png'.");
            }
            Quality = quality;
        }

When I post a file path like "c:\\abc.jpg", it will always throw exception say not right extension, I think, they should may be case ".bmp", ".png" and ".jpg"?

**Comment by higankanshi** [comment]
Yes, I think so, will be fixed

**Comment by funwaywang** [comment]
thank you very much 非常感谢 :)

**Comment by higankanshi** [comment]
Fixed
