### ISSUE TITLE
XAML Designer repot "VlcMediaPlayer doesn't have initialize" exception

### ISSUE THREAD

**Issue by HPDell** [higankanshi/Meta.Vlc#234]
我在MainWindow中引用了一个UserControl，UserControl中包含一个VlcPlayer，然后在设计时MainWindow报错如下：
> **InvalidOperationException: VlcMediaPlayer doesn't have initialize.**
   在 Meta.Vlc.Wpf.VlcPlayer.ThrowIfNotInitialize()
   在 Meta.Vlc.Wpf.VlcPlayer.LoadMedia(Uri uri)
   在 FGISClient.UIControls.UserContorl.VideoFullScreenPlayer.UserControl_Loaded(Object sender, RoutedEventArgs e)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

但是在UserControl中没有这个异常。请问此问题该如何解决？

**Comment by higankanshi** [comment]
所以你不应该在 UserControl 的 Loaded 事件中就开始播放视频...
播放视频这种东西应该等待 VlcPlayer 初始化完成之后才能开始

**Comment by HPDell** [comment]
我设置的是点击播放按钮开始播放视频，这样应该可以吧？

**Comment by LGinC** [comment]
libPath设置了否，LoadMedia调用了否

**Comment by HPDell** [comment]
都设置了，运行起来是可以的，但是设计时不可以
