### ISSUE TITLE
Event if properties have been set

### ISSUE THREAD

**Issue by Symbai** [higankanshi/Meta.Vlc#254]
I'm trying to get information about AudioTrackCount immediately after start playing a media like this:

```
Media.LoadMedia(somefile);
Media.Play();
 for (int i = 0; i < Media.AudioTrackCount; i++)
                {
                   //something
                }
```

 but at this time the AudioTrackCount is always 0. Once the video has actually started the AudioTrackCount is 2 as expected so there is a short delay.

Is there any existing event that occurs once after all properties have been set? Something like Media.VlcMediaPlayer.Opened ?

**Comment by higankanshi** [comment]
Maybe `VlcPlayer.StateChanged` event
