### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by collindoyle** [higankanshi/Meta.Vlc#255]
Hi I am having problem while starting the sample project program.

When I cloned and built the project with Framework 3.5, one error is detected and the compile failed.
The failed code is : 

`            StateChanged?.Invoke(this, new ObjectEventArgs<MediaStateChangedArgs>(new MediaStateChangedArgs {NewState = actualState }));
        }`

And it says the '.' is invalid.

By the way my IDE is Visual Studio 2013.  

Wish some one can kindly reply to it, thank you.

**Comment by higankanshi** [comment]
Using C# Language 6 to compile it.
