### ISSUE TITLE
请问能不能获取到每一帧的图像呢

### ISSUE THREAD

**Issue by Thxzzzzz** [higankanshi/Meta.Vlc#258]
如题，我需要对每一帧图像都进行处理（人脸检测识别之类的）
但是使用demo测试的时候发现 Player.VideoSourceChanged += PlayerOnVideoSourceChanged;
只有第一次出发的时候会进入事件，所以不知道该怎么操作，希望作者有空能解答

**Comment by Thxzzzzz** [comment]
期待更新 0.0

**Comment by higankanshi** [comment]
唔，没啥时间维护这个了，欢迎 PR

**Comment by Thxzzzzz** [comment]
emmm...太菜了还不会 QAQ

**Comment by Thxzzzzz** [comment]
QAQ看了半天，没看懂
