### ISSUE TITLE
Is this project supported by the developer?

### ISSUE THREAD

**Issue by b01110011** [higankanshi/Meta.Vlc#269]
I looked that the last update was a year ago.
The page with the documentation disappeared. (https://higan.me/Meta.Vlc/api/index.html)
VlcMediaPlayer.VlcInstance.VlmGetLength returns integer value (in microseconds), if duration of video more 71 minutes, it will return an incorrect value.

**Comment by higankanshi** [comment]
Are you using VLM functions? `Vlm*` functions onlu work with VLM...

Ummm...This repo has some limited support(some Q&A and some advices), I think I will not add functions for it anymore. But if you want to create a PR for it, I will check and merge it. I am happy to see someone willing to take over and provide maintenance for the repo.

This repo is targeted for VLC 2.x, but it is easy to support 3.x I think.

**Comment by b01110011** [comment]
yes, I checked on a 20 minute video, returns a positive result in microseconds. (should be in milliseconds)
I checked on a 2-hours video, and returned a negative result, there is an overflow of an integer value.
(the result is negative because the sign bit becomes 1)

**Comment by b01110011** [comment]
Thank you for such a good project!
I just decided to report an error!

**Comment by higankanshi** [comment]
Check this, [libvlc_vlm_get_media_instance_length](http://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__vlm.html#ga5d8b7bd36576ea8b7ea7910359ba4b5a)
 
I found it return a int, if the result is just a `int`, microseconds is not a suitable unit.
I created those bindings from official‘s doc, no idea with wrong unit, maybe you can try another version of vlc, maybe it is a bug of libvlc.

In fact, in my dev experience of VLC, I don't think libvlc is a good lib for play a media, libvlc has many bad design as a media lib, but VLC is a good meida player. For lib, I'm more inclined to ffmpeg.

**Comment by higankanshi** [comment]
In addition, I think `int` is not a suitable type for time unit, even milliseconds, if I were developer of libvlc, I will use `longlong` for it.
