### ISSUE TITLE
Latest supported LibVlc version with no major issues

### ISSUE THREAD

**Issue by muminasaad** [higankanshi/Meta.Vlc#271]
Can someone help me with this information?
What is the latest supported LibVlc version that can be downloaded from from VideoLab site that is compatible with Meta.Vlc Package?

**Comment by higankanshi** [comment]
Check [Meta.Vlc.Lib](https://www.nuget.org/packages/Meta.Vlc.Lib/) on nuget.
Check [LibVlc.2.2.-.xZune.7z](https://github.com/higankanshi/Meta.Vlc/releases/tag/v2.2.15.1222) on release.

**Comment by higankanshi** [comment]
BTW, I think 2.x is good for Meta.Vlc, if you can provide some code for this project, 3.0 is not hard to support

**Comment by muminasaad** [comment]
@higankanshi  i will do my best on supporting 3.x, after finishing my tests.
I used the LibVlc already added to the git hub project, can you remember which specific fix you used? 2.2.0 or 2.2.5?
And if you ever done some testing on 2.2.5 the latest can you tell me your results? 

I would be gratefull for your help :100:

**Comment by higankanshi** [comment]
See this wiki [Compile VLC for Meta.Vlc](https://github.com/higankanshi/Meta.Vlc/wiki/Compile-VLC-for-Meta.Vlc)...I think I develped base on 2.2.0
