### ISSUE TITLE
Not loading media after playing one AccessViolationException

### ISSUE THREAD

**Issue by anhlunnhaque** [higankanshi/Meta.Vlc#95]
Hi,

I have an exception very similar to this #42  I have the latest code. Same problem. I played the 1st file to the end. The player State == Ended. From there I tried to load another file to play. It throw an exception.

Thanks.
![playexceptionstatestopped](https://cloud.githubusercontent.com/assets/16323974/13902704/0b05d932-ee22-11e5-934b-575d3fb600f5.PNG)

**Comment by higankanshi** [comment]
Yeah, this bug has been report by many people, but I can't get the same exception with it, I don't know why, can we chat on gitter? I want to get more information about this bug.

**Comment by higankanshi** [comment]
Yeah, this bug has been report by many people, but I can't get the same exception with it, I don't know why, can we chat on gitter? I want to get more information about this bug.

**Comment by higankanshi** [comment]
Yeah, this bug has been report by many people, but I can't get the same exception with it, I don't know why, can we chat on gitter? I want to get more information about this bug.

**Comment by higankanshi** [comment]
Yeah, this bug has been report by many people, but I can't get the same exception with it, I don't know why, can we chat on gitter? I want to get more information about this bug.

**Comment by higankanshi** [comment]
I have tried with those code:
```CSharp
private void Player_StateChanged(object sender, ObjectEventArgs<Interop.Media.MediaState> e)
{
    if (e.Value == MediaState.Ended)
    {
        Player.BeginStop(() =>
            {
                Player.LoadMedia(@"E:\Video\test.mp4");
                Player.Play();
            });
    }
}
```

**Comment by anhlunnhaque** [comment]
Here's the fastest way to reproduce this bug using the WpfSample - .Net 4.5 project
1. Use the Load button to load a file and play it.
 private void Load_Click(object sender, RoutedEventArgs e)
        {
            var openfiles = new OpenFileDialog();
            if (openfiles.ShowDialog() == true)
            {
                Player.BeginStop(() =>
                {
                    Player.LoadMedia(openfiles.FileName);
                    Player.Play();
                });
            }
            return;
}

2. While that is play the first file. Use the Play button to load and play it.
private void Play_Click(object sender, RoutedEventArgs e)
        {
            string path = @"C:\Temp\temp.avi";
            Player.BeginStop(() =>
            {
                Player.LoadMedia(path);
                Player.Play();
            });
            //Player.Play();
        }

Like I said. That is the fastest way to get the error. In my case. I load & play 1 file to the end. Once the first file played completely. I try to load and play another file. That's where the exception is throw. I am guessing because the player is still lock from the first file and I am trying to load and play the second file.
P.S. This same problem occurs in vlcnet as well. My work around was to stop it before it reaches State == Ended.

Thanks.

**Comment by higankanshi** [comment]
I can't reproduce this bug, with your code.
![Sample](https://cloud.githubusercontent.com/assets/9367842/13905745/8ab222e4-ef03-11e5-9be7-162379b7e793.png)

With those code:
```CSharp
private void Load_Click(object sender, RoutedEventArgs e)
{
    var openfiles = new OpenFileDialog();
    if (openfiles.ShowDialog() == true)
    {
        Player.BeginStop(() =>
        {
            Player.LoadMedia(openfiles.FileName);
            Player.Play();
        });
    }
}

private void Play_Click(object sender, RoutedEventArgs e)
{
    string path = @"E:\Video\Anime\Expelled From Paradise.1080p\[KTXP&VCB-S] Expelled From Paradise [Movie][1080p][x264_aac].mp4";
    Player.BeginStop(() =>
    {
        Player.LoadMedia(path);
        Player.Play();
    });
}
```

**Comment by anhlunnhaque** [comment]
That's weird. Just to make sure. I downloaded the latest code and change the code and it threw an exception right when I click Play while the 1st file is playing. Maybe we can use teamviewer and you can log in to my system to take a look?
Thanks.

**Comment by higankanshi** [comment]
Ummm, Ok, we need to  arrange an appointment for TeamViewer.

At those time you can contact me by Gitter or E-Mail.

> 16:00-18:00 ( Beijing,China )
> 08:00-10:00 ( UTC )
> or
> 20:00-22:00 ( Beijing,China )
> 12:00-14:00 ( UTC )

**Comment by higankanshi** [comment]
@Transigent 
Yes, it is known issue for xZune.Vlc, I don't know why it happened, but this issue only happened with Windows 7, but clean Windows 7 (new install) is work fine.

I think it is a issue for LibVlc (Compatibility issues with system or other app).

**Comment by coczero** [comment]
I have the same problem, I sometimes get a AcessViolationExcaption at the same spot.
I can't reproduce it safely it is always random.

**Comment by higankanshi** [comment]
Try VlcPlayer.Rebuild() after stop media or before load a new media.

**Comment by JGH-GOU** [comment]
我也遇到了这个问题，我发现问题出在VlcEventManager的Dispose方法中的LibVlcManager.Free(InstancePointer);
![image](https://cloud.githubusercontent.com/assets/18373724/15596547/11a5a6a0-23fb-11e6-8e04-3a21fbf160d5.png)
我把这一行注解掉就没有ERROR了，我把测试视频上传到Youtube
https://www.youtube.com/watch?v=-2HwaGXZHKI
在读取视频时Meta.Vlc.Wpf的VlcPlayer会先把既有的VlcMedia Dispose掉，
这里会触发VlcEventManager的Dispose方法，
![image](https://cloud.githubusercontent.com/assets/18373724/15596790/d6362278-23fc-11e6-9753-e6d0321afc49.png)
另外这个BUG可能跟内存有关，上次出现BUG的时候我把PC上一些占内存的程序关掉，BUG就没出现了，还有载入档案较大的视频出现BUG的机率也比较高一些，有什么想法吗?

**Comment by higankanshi** [comment]
@JGH-GOU 这个 BUG 主要是在 Win7 上面出现比较频繁，Win8 和 Win10 都基本没有出现过，我在想可能是 VLC 他的问题，不过既然知道了是事件管理器的原因...应该会好找很多...

**Comment by epsi1on** [comment]
hi,
I'm getting same problem in a specific machine (not mine)! and that is very odd.
How can i give you more technical info about this exception?

**Comment by higankanshi** [comment]
@epsi1on 
we have some progress with it, the reason of case this issue is that event manager of old media have been free, but in some platform(like Windows 7), VLC will use it in creating new media, I don't know why.

But, in current version of Meta.Vlc you can use VlcPlayer.Rebuild() method to rebuild a media player.

In next version, I will test if we don't free event manager of old media, what will be happened.

**Comment by epsi1on** [comment]
i'll test VlcPlayer.Rebuild(), however on that machine (which have problem) there was no such a problem since last week :8ball: but suddenly turned this way...

**Comment by mcolleoni** [comment]
Hi, with VlcPlayer.RebuildPlayer() the library throws the same error on Stop().

**Comment by mcolleoni** [comment]
@higankanshi, I think I've (perhaps) solved, adding in VlcPlayer.LoadMedia() (and all its variations) the highlighted line:

![cattura](https://cloud.githubusercontent.com/assets/22749154/19528070/eb045b48-962a-11e6-9a21-c4e625041498.PNG)

I hope this help.

**Comment by higankanshi** [comment]
@mcolleoni Thanks for your contributions, I will add it to Meta.Vlc, or you can create a  PR.
